// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChromaHeader: typeof import('./components/chroma-header.vue')['default']
    HomeButton: typeof import('./components/home-button.vue')['default']
    ProjectCard: typeof import('./components/project-card.vue')['default']
  }
}

export { }
